- name: Sample IOS config for Ansible 2.5+
  hosts: Cisco
  
  gather_facts: no
  vars_prompt:
    - name: loopback_num
      prompt: "What Loopback Number to Delete?"
      private: no

  tasks:

  - name: Delete loopback {{loopback_num}}
    cisco.ios.ios_interfaces:
      config:
        - name: Loopback{{loopback_num}}
          enabled: true
          description: created with ansible!
      state: purged #deletes the logical interface
